/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class NotaVista extends javax.swing.JFrame {

    /**
     * Creates new form NotaVista
     */
    public NotaVista() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaResultado = new javax.swing.JTextArea();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sistema de Notas");

        areaResultado.setColumns(20);
        areaResultado.setRows(5);
        jScrollPane1.setViewportView(areaResultado);

        btnMenu.setText("Abrir Menú");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaVista().setVisible(true);
            }
        });
    }

    public int menuInicio() {
    String[] opciones = {
        "1. Definir Cantidad",
        "2. Agregar Estudiante",
        "3. Resultados Definitivos",
        "4. Lista por Nota Límite",
        "5. Incrementar Desarrollo",
        "6. Modificar Nota",
        "7. Salir"
    };
    int sel = javax.swing.JOptionPane.showOptionDialog(this,
        "Seleccione una opción:",
        "MENÚ PRINCIPAL",
        javax.swing.JOptionPane.DEFAULT_OPTION,
        javax.swing.JOptionPane.PLAIN_MESSAGE,
        null, opciones, opciones[0]);

    return sel == -1 ? 7 : sel + 1;
}

    public void mostrarMensaje(String mensaje) {
        areaResultado.setText(mensaje); // muestra en el JFrame
    }

    public int pedirCantidadEstudiantes() {
        return Integer.parseInt(javax.swing.JOptionPane.showInputDialog(this, "¿Cuántos estudiantes?"));
    }
    public String pedirNombre() {
        return javax.swing.JOptionPane.showInputDialog(this, "Nombre del estudiante:");
    }
    public int pedirCodigo() {
        return Integer.parseInt(javax.swing.JOptionPane.showInputDialog(this, "Código (mayor a 21000):"));
    }
    public double pedirNotaS() {
        return Double.parseDouble(javax.swing.JOptionPane.showInputDialog(this, "Nota Software (0.0-5.0):"));
    }
    public double pedirNotaH() {
        return Double.parseDouble(javax.swing.JOptionPane.showInputDialog(this, "Nota Hardware (0.0-5.0):"));
    }
    public double pedirNotaM() {
        return Double.parseDouble(javax.swing.JOptionPane.showInputDialog(this, "Nota Matemáticas (0.0-5.0):"));
    }
    public double pedirNotaLimite() {
        return Double.parseDouble(javax.swing.JOptionPane.showInputDialog(this, "Nota límite (0.0-5.0):"));
    }
    public double pedirIncrementoDesarrollo() {
        return Double.parseDouble(javax.swing.JOptionPane.showInputDialog(this, "Incremento (0.0-0.5):"));
    }
    public int pedirBuscarCodigo() {
        return Integer.parseInt(javax.swing.JOptionPane.showInputDialog(this, "Código del estudiante:"));
    }
    public void setBotonMenuListener(java.awt.event.ActionListener listener) {
    btnMenu.addActionListener(listener);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaResultado;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
